include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true

    prefer_const_declarations: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    avoid_dynamic_calls: true
    cancel_subscriptions: true
    avoid_print: true
